### ISSUE TITLE
Release teaspoon-jasmine 2.9.1 and 2.4.1 via rubygems.org

### ISSUE THREAD

**Issue by CloCkWeRX** [jejacks0n/teaspoon#553]
e93d3ac1b67377d6c8622b2daf01471a525367d5 Bumped the gem to 2.4.1
a509c2ef52800949a564f86119b4576bcbba5e07 Bumped to 2.9.1

... but https://rubygems.org/gems/teaspoon-jasmine only has 2.3.4.

**Comment by baburdick** [comment]
Release teaspoon as well. Last release to rubygems is 3 years ago (v1.1.5). Lots of valuable changes since then.

If access has been lost, make a new account and release as `jejacks0n-teaspoon`, etc.

**Comment by localhostdotdev** [comment]
sorry for the bump but I was having a hard time getting chrome headless to work and then looking at the source I saw it was an older version I was using (from 4 years ago (October 09, 2015), teaspoon being last released 3 years ago (March 25, 2016))

**Comment by mathieujobin** [comment]
trying to upgrade a project to ruby 2.4

teaspoon is my only issue left...

**Comment by mathieujobin** [comment]
I just pushed to rubygems
```
mj-teaspoon-1.1.4.pre.e93d3ac.gem
mj-teaspoon-jasmine-2.4.1.pre.e93d3ac.gem
mj-teaspoon-1.1.5.pre.a509c2e.gem
mj-teaspoon-jasmine-2.9.1.pre.a509c2e.gem
```

@CloCkWeRX @baburdick @localhostdotdev @jejacks0n 

thinking to push latest master as well

**Comment by danmayer** [comment]
can we get a release cut?

**Comment by mathieujobin** [comment]
looks like we have

**Comment by mikewindow** [comment]
Will the teaspoon-jasmine gem be updated on rubygems? https://rubygems.org/gems/teaspoon-jasmine still shows 2.3.4 as the latest version.

**Comment by mikewindow** [comment]
@mathieujobin Is mj-teaspoon-jasmine the official replacement for teaspoon-jasmine?

https://rubygems.org/gems/mj-teaspoon-jasmine

**Comment by jejacks0n** [comment]
I can add somebody as a maintainer if you'd like.

**Comment by thebravoman** [comment]
What really is the difference between the two - teaspoon-jasmin vs mj-teaspoon-jasmin? https://rubygems.org/search?utf8=%E2%9C%93&query=teaspoon-jasmine

**Comment by mikewindow** [comment]
The teaspoon-jasmine, teaspoon-mocha, and teaspoon-qunit gems haven't been updated since 2015. The main teaspoon gem has been updated on rubygems and seems like it an oversight that the framework gems updates weren't uploaded.

**Comment by mikewindow** [comment]
mj-teaspoon-jasmine is a snapshot of teaspoon-jasmine 2.9.1 alpha before rails 6 was fully supported.

https://rubygems.org/gems/mj-teaspoon-jasmine/versions/2.9.1.pre.a509c2e
https://github.com/jejacks0n/teaspoon/commit/a509c2e

**Comment by mikewindow** [comment]
@mathieujobin Are you planning to update your mj-teaspoon-jasmine gem?

**Comment by mathieujobin** [comment]
> @mathieujobin Is mj-teaspoon-jasmine the official replacement for teaspoon-jasmine?
> 
> https://rubygems.org/gems/mj-teaspoon-jasmine

No the mj- prefixed was an attempt but it's no good. I should Yank it.

This gem is very annoying to rename has it contains multiple with dependencies

We need a new maintainer to make an official release

**Comment by mathieujobin** [comment]
@jejacks0n give me access, I'll push those

**Comment by mathieujobin** [comment]
```
Successfully registered gem: teaspoon-jasmine (2.4.1)
Successfully registered gem: teaspoon-jasmine (2.9.1)
```
